#!/usr/bin/env bash
# Displays information about subdomains of a given domain

get_record() {
    local domain="$1"
    local sub="$2"
    dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | \
        awk -v s="$sub" '{print "The subdomain " s " is a " $4 " record and points to " $5}'
}

if [ -z "$2" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_record "$1" "$sub"
    done
else
    get_record "$1" "$2"
fi
